scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:9090
  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node-exporter
    scrape_interval: 15s
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: authors
    scrape_interval: 15s
    static_configs:
      - targets:
          - authors:8081
  - job_name: books
    scrape_interval: 15s
    static_configs:
      - targets:
          - books:8082